name: Test and Build Reports Scheduler

on: [push, pull_request]

env:
  OPENSEARCH_VERSION: '1.3.0-SNAPSHOT'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 14
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # reports-scheduler
      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: RunBackwards Compatibility Tests
        run: |
          cd reports-scheduler
          echo "Running backwards compatibility tests ..."
          ./gradlew bwcTestSuite


      - name: Build with Gradle
        run: |
          cd reports-scheduler
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: reports-scheduler
          directory: reports-scheduler/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./reports-scheduler/build/distributions/*.zip reports-scheduler-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: reports-scheduler
          path: reports-scheduler-builds

