name: Test and Build Reports Scheduler

on: [push, pull_request]

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  linux-build:
    needs: Get-CI-Image-Tag
    strategy:
      matrix:
        java:
          - 21
    runs-on: ubuntu-latest
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: --user root

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: RunBackwards Compatibility Tests
        run: |
          echo "Running backwards compatibility tests ..."
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c "./gradlew bwcTestSuite"

      - name: Build with Gradle
        run: |
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c "./gradlew build"

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: reports-scheduler
          directory: reports-scheduler/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./build/distributions/*.zip reports-scheduler-builds/
          chown -R 1000:1000 `pwd`

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-scheduler-linux
          path: reports-scheduler-builds

  windows-build:
    strategy:
      matrix:
        java:
          - 21
    runs-on: windows-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          ./gradlew.bat build

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./build/distributions/*.zip reports-scheduler-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-scheduler-windows
          path: reports-scheduler-builds
  
  macos-build:
    strategy:
      matrix:
        java:
          - 21
    runs-on: macos-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # reports-scheduler
      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./build/distributions/*.zip reports-scheduler-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-scheduler-macos
          path: reports-scheduler-builds
